# Generated by Django 4.2.4 on 2023-08-19 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_line', models.CharField(choices=[('Jardineria', 'Jardineria'), ('Ferreteria', 'Ferreteria'), ('Almacen', 'Almacen'), ('Tecnologia', 'Tecnologia'), ('Otros', 'Otros')], default='Otros', max_length=128)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name_product', models.CharField(max_length=140)),
                ('description', models.TextField(max_length=1200)),
                ('code_product', models.CharField(max_length=10)),
                ('expiration', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
