# Generated by Django 4.2.4 on 2023-08-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_product',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
