# Generated by Django 4.2.4 on 2023-09-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_stockproduct_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproduct',
            name='code_product',
            field=models.CharField(max_length=10),
        ),
    ]
