# Generated by Django 4.2.4 on 2023-10-01 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, default='')),
                ('client_question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_question', to=settings.AUTH_USER_MODEL)),
                ('client_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
