# Generated by Django 4.2.4 on 2023-08-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartitem_remove_cart_item_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='update_at',
            field=models.DateTimeField(null=True),
        ),
    ]
