# Generated by Django 4.2.4 on 2023-09-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_cart_cartitem_delete_cartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
