# Generated by Django 4.2.4 on 2023-08-29 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stockproduct_remove_stock_product_user'),
        ('cart', '0006_cart_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stockproduct'),
        ),
    ]
